services:
  - type: web
    name: national-parks-scraper
    runtime: python
    plan: free
    region: oregon
    buildCommand: |
      pip install -r requirements.txt
      playwright install chromium
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
